#!/usr/bin/env bash
#A script that backup all MYSQL databases

mysqldump -u root --password=$1 --all-databases > backup.sql

DATE_FORMAT=$(date +"%d-%m-%Y")

tar -czvf "$DATE_FORMAT.tar.gz" backup.sql
