#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
j=1
while [ "$j" -le 100 ]
do
    if [ $((j % 15)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((j % 5)) -eq 0 ]
    then
        echo "Buzz"
    elif [ $((j % 3)) -eq 0 ]
    then
        echo "Fizz"
    else
        echo "$j"
    fi
    j=$((j + 1))
done
j=$j
